# Generated by Django 4.0 on 2022-09-13 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='dateof',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
